<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S552G9G" failures="1" tests="6" name="practice.test.RetryAlalyserTest" time="0.081" errors="0" timestamp="27 Aug 2024 06:19:53 GMT" skipped="5">
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.006">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.002">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.005">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at practice.test.RetryAlalyserTest.activateSim(RetryAlalyserTest.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.063">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.003">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice.test.RetryAlalyserTest" name="activateSim" time="0.002">
    <skipped/>
  </testcase> <!-- activateSim -->
</testsuite> <!-- practice.test.RetryAlalyserTest -->
